refacto(tests): update use case tests
OpenClassrooms/CodeGenerator pull request #40
Opened 2020-11-04 14:12 UTC by killianherbunot

2020-11-04 14:31 UTC, nnguon approved these changes

2020-11-04 14:33 UTC, thomasgataly approved these changes

2020-11-04 15:35 UTC, arnaud-23 requested changes

2020-11-04 15:35 UTC, arnaud-23 commented on src/Skeleton/Tests/BusinessRules/UseCases/GenericUseCaseTest.php.twig
>  class {{ skeletonModel.shortName }} extends TestCase
final

2020-11-04 15:35 UTC, arnaud-23 commented on src/Skeleton/Tests/BusinessRules/UseCases/GenericUseCaseTest.php.twig
>      final public function {{ skeletonModel.genericUseCaseTestMethod }}ReturnResponse(): void
not final if class is final

2020-11-04 15:35 UTC, arnaud-23 commented on tests/Fixtures/Classes/Tests/BusinessRules/UseCases/Domain/SubDomain/GenericUseCaseTest.php
>  class GenericUseCaseTest extends TestCase
final

2020-11-04 15:35 UTC, arnaud-23 commented on tests/Fixtures/Classes/Tests/BusinessRules/UseCases/Domain/SubDomain/GenericUseCaseTest.php
>      final public function genericUseCaseReturnResponse(): void
not final

2020-11-04 15:35 UTC, arnaud-23 commented on tests/Fixtures/Classes/Tests/BusinessRules/UseCases/Domain/SubDomain/GetFunctionalEntitiesTest.php
>      final public function withoutFunctionalEntitiesReturnEmpty(): void
not final but class should be final

2020-11-04 15:35 UTC, arnaud-23 commented on tests/Fixtures/Classes/Tests/BusinessRules/UseCases/Domain/SubDomain/GetFunctionalEntityTest.php
>      final public function getFunctionalEntityShouldReturnResponse(): void
not final but class should be final

2020-11-24 13:03 UTC, fredericjaume-oc approved these changes

2021-03-22 20:23 UTC, merged