refacto(generic-usecase): remove builder, BuilderImpl, DTO and refact…
OpenClassrooms/CodeGenerator pull request #41
Opened 2020-11-05 13:05 UTC by arnaud-23

…o request as static creation

2020-11-05 13:34 UTC, yassavic commented
@arnaud-23 Why did you remove Request Builder?
I understand for the DTO.

2020-11-05 19:13 UTC, sidux commented
@yassavic I'd think if we don't need interface for the DTO, we probably don't need it either for the builder, (even if for cases when we can have multiple builder implementations for the same DTO that's still very rare)

2020-11-05 19:17 UTC, sidux approved these changes

2020-11-05 20:54 UTC, romainkuzniak requested changes
I didn't read all the PR but unsure:
- if you remove the interface, previous DTOs are not suffixed with DTO
- previous DTOs should still be in Request folder in UseCases
- same for builder

2020-11-06 09:38 UTC, arnaud-23 commented
> I didn't read all the PR but unsure:
> 
> * if you remove the interface, previous DTOs are not suffixed with DTO
> * previous DTOs should still be in Request folder in UseCases
> * same for builder

@romainkuzniak no builder anymore that what we said, to use a static create from the request, isn't it ?

2020-11-06 09:49 UTC, arnaud-23 commented
@romainkuzniak I don't understand why it should be in UseCase/Request/DTO ?

2020-11-06 09:54 UTC, arnaud-23 commented on tests/Fixtures/Classes/BusinessRules/Requestors/Domain/SubDomain/GenericUseCaseRequest.php
> +    }
here is the change

2020-11-06 09:54 UTC, arnaud-23 commented on tests/Fixtures/Classes/BusinessRules/Requestors/Domain/SubDomain/GenericUseCaseRequestBuilder.php
> -}
here is the change

2020-11-06 09:54 UTC, arnaud-23 commented on tests/Fixtures/Classes/BusinessRules/UseCases/Domain/SubDomain/DTO/Request/GenericUseCaseRequestBuilderImpl.php
> -}
here is the change

2020-11-06 09:54 UTC, arnaud-23 commented on tests/Fixtures/Classes/BusinessRules/UseCases/Domain/SubDomain/DTO/Request/GenericUseCaseRequestDTO.php
> -}
here is the change

2020-11-06 09:54 UTC, arnaud-23 commented on tests/Fixtures/Classes/Tests/BusinessRules/UseCases/Domain/SubDomain/GenericUseCaseTest.php
> +    public function genericUseCaseReturnResponse(): void
here is the change

2020-11-06 09:54 UTC, arnaud-23 commented on tests/Fixtures/Classes/Tests/BusinessRules/UseCases/Domain/SubDomain/GenericUseCaseTest.php
> +        return GenericUseCaseRequest::create();
here is the change

2020-11-06 10:08 UTC, yassavic approved these changes

2020-11-06 10:14 UTC, sidux commented
@arnaud-23 if we respect the CRP principle then we should but the UseCase Request/Response next to files where is it used, and that's the usecases (where we put our DTO's right now) that rule can change if the same request/response is used in multiple usecases from other domains, but that nearly never happens.
So I think we should replace DTO folder by Request and Response folders

2020-11-06 10:26 UTC, sidux commented
@romainkuzniak @arnaud-23 I was the one who suggested to use static constructor (create) instead of Builders, my reason was the same as for interfaces that we don't really take advantage of the pattern by sharing the same building sequence between multiple implementations or at least it's really rare.
The advantage of having a static constructor in the other hand is that you'll need to inject only the usecase when using it which makes our dependencies a bit cleaner.

That being said, Im assuming that we all know when we really need a builder to be able to create it when needed.

2020-11-13 10:23 UTC, merged